disabled_rules:
  - trailing_whitespace
  - line_length
  - cyclomatic_complexity
  - function_body_length
  - file_length
  - force_cast
  - type_body_length

included:
  - iOS
  - Shared

excluded:
  - Pods
  - .build
  - .swiftpm
